version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - '2182:2182'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      # - zookeeper-logs:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: zookeeper
      # KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101
    networks:
      - rmoff_kafka

  kafka_local_dev_1:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    container_name: kafka_local_dev_1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 1
      # KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000
      KAFKA_LOG_RETENTION_HOURS: 240
      KAFKA_LOG_RETENTION_BYTES: 536870912000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: kafka
      # KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101
    networks:
      - rmoff_kafka

  kafka_local_dev_2:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka2
    container_name: kafka_local_dev_2
    restart: always
    depends_on:
      - zookeeper
      - kafka_local_dev_1
    ports:
      - '9093:9093'
    volumes:
      - kafka:/kafka
    environment:
      KAFKA_BROKER_ID: 2
      # KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000
      KAFKA_LOG_RETENTION_HOURS: 240
      KAFKA_LOG_RETENTION_BYTES: 536870912000
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: kafka
      # KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101
    networks:
      - rmoff_kafka

  kafka_ui:
    image: provectuslabs/kafka-ui
    hostname: kafka_ui
    container_name: kafka_ui
    restart: always
    ports:
      - '9000:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka_local_dev_1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_BROKERCONNECT: kafka:29092
      KAFKA_CLUSTERS_1_NAME: kafka_local_dev_2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka2:9093
      KAFKA_02_BROKERCONNECT: kafka2:29093
    depends_on:
      - kafka_local_dev_1
      - kafka_local_dev_2
      - zookeeper
    networks:
      - rmoff_kafka

volumes:
  kafka:
  zookeeper-data:

networks:
  rmoff_kafka:
    name: rmoff_kafka